In [ ]:
import numpy as np

def print_matrix(matrix):
  print('\n'.join([''.join(['{:4}'.format(item) for item in row]) for row in matrix]))


def average_and_standard_deviation(matrix):
  average_row = []
  average_row = [np.median(row) for row in matrix]

  standard_deviation_row = []
  standard_deviation_row = [np.std(row) for row in matrix]
  
  average_col = [] 
  average_col = [np.median(col) for col in matrix]
  
  standard_deviation_col = []
  standard_deviation_col = [np.std(col) for col in matrix]
 
  print("Média linhas matriz → ", average_row)
  print("Desvio padrão linhas matriz → ", standard_deviation_row)

  print("Média linhas matriz → ", average_col)
  print("Desvio padrão colunas matriz → ", standard_deviation_col)




if __name__ == "__main__":
  ExA = [[12,9,4,1],[11,5,8,1],[1,2,3,1]]
  print('ExA')
  print_matrix(ExA)
  print('\n')

  ExB = [[1,5],[1,7],[1,9],[1,1]]
  print('ExB')
  print_matrix(ExB)
  print('\n')

  ExC = np.random.randint(0,100,(3,3))
  print('ExB')
  print_matrix(ExC)
  print('\n')
  print('\nDados matriz ExA')
  average_and_standard_deviation(ExA)
  print('\nDados matriz ExC')
  average_and_standard_deviation(ExC)
  print('\n')


  ExA = np.matrix(ExA)
  ExD = []
  ExD = ExA[:,-2:]
  print('\nMatriz ExD')
  print(ExD)
  print('\n')
  print('\nMatriz ExE')
  p1 = ExA[0:2,]
  print('P1\n',p1)
  p2 = np.transpose(ExA[:,0:2])
  print('P2\n',p2)
  Exe = np.concatenate((p1,p2),1)
  print('\nMatriz ExE')
  print(ExE)

ExA
  12   9   4   1
  11   5   8   1
   1   2   3   1


ExB
   1   5
   1   7
   1   9
   1   1


ExB
  18  38  89
   6  97  60
  45  99  61



Dados matriz ExA
Média linhas matriz →  [6.5, 6.5, 1.5]
Desvio padrão linhas matriz →  [4.272001872658765, 3.6996621467371855, 0.82915619758885]
Média linhas matriz →  [6.5, 6.5, 1.5]
Desvio padrão colunas matriz →  [4.272001872658765, 3.6996621467371855, 0.82915619758885]

Dados matriz ExC
Média linhas matriz →  [38.0, 60.0, 61.0]
Desvio padrão linhas matriz →  [29.892399628593814, 37.366057086910075, 22.647050335284035]
Média linhas matriz →  [38.0, 60.0, 61.0]
Desvio padrão colunas matriz →  [29.892399628593814, 37.366057086910075, 22.647050335284035]



Matriz ExD
[[4 1]
 [8 1]
 [3 1]]



Matriz ExE
P1
 [[12  9  4  1]
 [11  5  8  1]]
P2
 [[12 11  1]
 [ 9  5  2]]

Matriz ExE
[[12  9]
 [11  5]]


In [ ]:
'''Função da validação de entradas'''

from typing import Any, Callable

def receive_value(type_value: Callable, message: str) -> Any:

    while True:
        value = input(f"{message} → ")

        try:
            return type_value(value)

        except ValueError:
            print(f"'{value}' não é válido, tente novamente.")

In [ ]:
import numpy as np
from random import sample
'''
def final_classification(names, matrix):
  average_lap = [np.median(col) for col in matrix]
  order = []
  for i in range(len(average_lap)):
    order.append(names[i],average_lap)
  print(order)
  
'''

def fasted_average_lap(matrix:np.matrix):

  average_lap = [np.median(col) for col in matrix]  

  best_average = np.amin(average_lap)

  which_lap = np.where(average_lap == best_average )

  return (which_lap, best_average)


def best_laps(matrix: np.matrix):

  best_lap_is = np.amin(matrix)

  which_best_lap = np.where(matrix == best_lap_is )

  return (which_best_lap, best_lap_is)

if __name__ == "__main__":

  laps = 10
  number_kart_racer=6

  matrix_lap_time = np.zeros((number_kart_racer,laps))

  names_kart_racer =[]

  option = receive_value(int, 'Deseja preencher manualmente?(1-Sim 0-Não)')
  if option: 

    for i in range(number_kart_racer):
      names_kart_racer.append(receive_value(str,'Nome?'))

      
      for j in range(laps):
        matrix_lap_time[i][j]= receive_value(float, f'Tempo da {j+1}ª volta?')
    
  else:
    names_kart_racer=['Mariana Serafim', 'Kelly Curie',' Janyce Da Cruz','Bia Figueiredo','Gabi Mesa','Antonella Bassani']

    matrix_lap_time = np.random.randint(18,25,size =(number_kart_racer,laps))


  print('\n Matriz dos tempos')
  print(matrix_lap_time)

  print('\n Melhor volta da prova')
  print(best_laps(matrix_lap_time))
  print('\n A volta com a média mais rápida')
  print (fasted_average_lap(matrix_lap_time))
  print('\n')

  #final_classification(names_kart_racer, matrix_lap_time)


Deseja preencher manualmente?(1-Sim 0-Não) → 0

 Matriz dos tempos
[[21 20 18 21 18 24 18 21 23 24]
 [18 23 19 19 23 18 23 24 24 20]
 [19 24 20 20 22 24 18 22 22 20]
 [20 23 24 23 22 18 18 23 18 19]
 [20 21 21 21 22 20 23 18 19 19]
 [22 23 21 24 22 22 23 24 23 18]]

 Melhor volta da prova
((array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5]), array([2, 4, 6, 0, 5, 6, 5, 6, 8, 7, 9])), 18)

 A volta com a média mais rápida
((array([4]),), 20.5)


